// Rung-2 pilot: generate FLUX.1 schnell silhouette candidates for the
// icon-miss backlog (see scripts/seed-library.ts's misses.json / AGENTS.md
// "text-to-2D rung"), downsample each with the same 16×16 front-mask path
// as the icon pipeline (scripts/lib/silhouette.ts), and write eyeball
// artifacts for Fable-tier review. Provider is auto-selected at runtime from
// whichever API key is present — no model calls happen until a key is set
// and --dry-run is absent.
//
// Usage: npx tsx scripts/gen-silhouettes.ts [flags]
//   --out=<runId>       output run id (default gen1-16char-flux)
//   --nouns=<list>      comma-separated filter (hyphenated for multi-word,
//                       e.g. palm-tree); default is all 16 nouns below
//   --candidates=N      candidates per noun, seeds 1..N (default 4)
//   --dry-run           print provider, prompts, image count, cost estimate;
//                       exit 0 WITHOUT calling anything (works with no key)
//   --yes               required if planned image count > 80 (safety cap)
//   --skip-existing     candidates whose raw/<stem>.png already exists are
//                       re-downsampled from disk instead of regenerated
//                       (resume a partial run without paying twice)
//   --date=<YYYY-MM-DD> manifest date (default 2026-07-05)
//   Reads:  TOGETHER_API_KEY or REPLICATE_API_TOKEN (env or project .env)
//   Writes: runs/<runId>/raw/<noun-stem>-c<i>.png      generated bytes
//           runs/<runId>/masks/<noun-stem>-c<i>.txt    16×16 front mask
//           runs/<runId>/previews/<noun-stem>-c<i>.png mask upscaled to 512²
//           runs/<runId>/gen.json                      manifest

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { Resvg } from '@resvg/resvg-js';
import { decodePng, isInkDark, pixelsToFrontMask } from './lib/silhouette.ts';
import { maskToRows } from '../src/bench/maskOps.ts';

const SIZE = 16;
const PREVIEW_PX = 512;
const CELL_PX = PREVIEW_PX / SIZE; // 32
const CONCURRENCY = 4;
const YES_THRESHOLD = 80;

// --- CLI flags (process.argv.slice(2)) — see the usage comment above. ---
function parseFlag(name: string): string | undefined {
  const prefix = `--${name}=`;
  const arg = process.argv.slice(2).find((a) => a.startsWith(prefix));
  return arg?.slice(prefix.length);
}
const hasFlag = (name: string) => process.argv.slice(2).includes(`--${name}`);

const OUT_RUN_ID = parseFlag('out') ?? 'gen1-16char-flux';
const NOUNS_FILTER = parseFlag('nouns')?.split(',').map((s) => s.trim());
const CANDIDATES = Number(parseFlag('candidates') ?? '4');
const DRY_RUN = hasFlag('dry-run');
const YES = hasFlag('yes');
const SKIP_EXISTING = hasFlag('skip-existing');
const MANIFEST_DATE = parseFlag('date') ?? '2026-07-05';

// --- Minimal .env loader: project-root .env, simple KEY=VALUE lines, no
// dotenv dep. Only sets vars not already present in process.env. ---
function loadDotEnv(): void {
  const envPath = join(import.meta.dirname, '..', '.env');
  if (!existsSync(envPath)) return;
  const text = readFileSync(envPath, 'utf8');
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = value;
  }
}
loadDotEnv();

// noun -> {subject, view} for the base prompt template. Names with spaces
// use the noun itself for prompt text but hyphens for filenames (see
// nounFileStem). 12 icon-miss nouns (seed3-16char-fa misses.json) + 4
// weak-icon retries (hat/tree/ice-cream-cone/rocket-ship: the FA glyph
// doesn't survive 16×16 downsampling as a legible silhouette — tiered
// profiles render as staircases, FA's rocket is diagonal). The retry
// prompts target those failures (single canopy, one scoop, upright).
type NounSpec = { subject: string; view: string };
const NOUN_TABLE: Record<string, NounSpec> = {
  table: { subject: 'a four-legged dining table', view: 'side view' },
  sword: { subject: 'a sword pointing straight up', view: 'front view, vertical' },
  lighthouse: { subject: 'a lighthouse tower', view: 'side view, vertical' },
  ladder: { subject: 'a straight ladder standing upright', view: 'front view, vertical' },
  fox: { subject: 'a fox standing', view: 'side profile view' },
  flower: { subject: 'a single flower with petals and stem', view: 'front view' },
  duck: { subject: 'a duck standing', view: 'side profile view' },
  mushroom: { subject: 'a mushroom with a wide cap and thick stem', view: 'side view' },
  snail: { subject: 'a snail with a spiral shell', view: 'side profile view' },
  penguin: { subject: 'a penguin standing', view: 'side profile view' },
  octopus: { subject: 'an octopus with hanging tentacles', view: 'front view' },
  'palm tree': { subject: 'a palm tree', view: 'side view' },
  hat: { subject: 'a cowboy hat', view: 'side view' },
  tree: {
    subject: 'a tree with a single rounded canopy and visible trunk',
    view: 'side view',
  },
  'ice cream cone': {
    subject: 'an ice cream cone with one round scoop',
    view: 'front view, vertical',
  },
  'rocket ship': { subject: 'a rocket ship pointing straight up', view: 'front view, vertical' },
};

/** Filename stem: spaces become hyphens (matches make-prompts.ts's convention). */
function nounFileStem(noun: string): string {
  return noun.replace(/\s+/g, '-');
}

function buildPrompt(spec: NounSpec): string {
  return (
    `flat solid black silhouette of ${spec.subject}, ${spec.view}, minimal flat icon style, ` +
    `pure white background, centered, no outline, no gradient, no text, no shading`
  );
}

// Resolve the noun list for this run: --nouns filters by file-stem match
// (hyphenated), default is every table entry.
const allNouns = Object.keys(NOUN_TABLE);
const selectedNouns = NOUNS_FILTER
  ? allNouns.filter((n) => NOUNS_FILTER.includes(nounFileStem(n)))
  : allNouns;

type Candidate = { noun: string; seed: number };
const candidates: Candidate[] = [];
for (const noun of selectedNouns) {
  for (let seed = 1; seed <= CANDIDATES; seed++) candidates.push({ noun, seed });
}

// --- Provider selection --------------------------------------------------
type Provider = 'together' | 'replicate' | 'none';

function selectProvider(): Provider {
  if (process.env.TOGETHER_API_KEY) return 'together';
  if (process.env.REPLICATE_API_TOKEN) return 'replicate';
  return 'none';
}

const PROVIDER = selectProvider();

// Together: 512² @ $0.0027/MP = 0.262144 MP * $0.0027 ≈ $0.000708/img.
// Replicate: flat $0.003/img.
const COST_PER_IMAGE: Record<Exclude<Provider, 'none'>, number> = {
  together: 0.000708,
  replicate: 0.003,
};

// --- Dry run --------------------------------------------------------------
if (DRY_RUN) {
  console.log(`provider: ${PROVIDER}`);
  if (PROVIDER === 'none') {
    console.log(
      'no API key found — set TOGETHER_API_KEY or REPLICATE_API_TOKEN in the environment ' +
        'or a project-root .env file to actually generate (dry-run only prints prompts/cost).',
    );
  }
  console.log(`nouns: ${selectedNouns.length}, candidates/noun: ${CANDIDATES}, ` +
    `total images: ${candidates.length}`);
  console.log('');
  for (const noun of selectedNouns) {
    console.log(`${noun} (${nounFileStem(noun)}): "${buildPrompt(NOUN_TABLE[noun])}"`);
  }
  if (PROVIDER !== 'none') {
    const cost = candidates.length * COST_PER_IMAGE[PROVIDER];
    console.log(`\nestimated cost (${PROVIDER}): $${cost.toFixed(4)}`);
  } else {
    console.log(
      `\nestimated cost if together: $${(candidates.length * COST_PER_IMAGE.together).toFixed(4)}, ` +
        `if replicate: $${(candidates.length * COST_PER_IMAGE.replicate).toFixed(4)}`,
    );
  }
  process.exit(0);
}

// --- Guardrails past this point: real calls are possible. ---
if (PROVIDER === 'none') {
  console.error(
    'gen-silhouettes: no provider configured. Set TOGETHER_API_KEY or REPLICATE_API_TOKEN ' +
      '(env var or project-root .env) and re-run, or use --dry-run to preview without a key.',
  );
  process.exit(1);
}
if (candidates.length > YES_THRESHOLD && !YES) {
  console.error(
    `gen-silhouettes: planned ${candidates.length} images exceeds the ${YES_THRESHOLD}-image ` +
      `safety cap. Re-run with --yes to confirm, or narrow --nouns/--candidates.`,
  );
  process.exit(1);
}

// --- Simple concurrency pool ----------------------------------------------
async function runPool<T, R>(
  items: T[],
  limit: number,
  worker: (item: T) => Promise<R>,
): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;
  async function runNext(): Promise<void> {
    const i = next++;
    if (i >= items.length) return;
    results[i] = await worker(items[i]);
    await runNext();
  }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, () => runNext()));
  return results;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// --- Providers --------------------------------------------------------------
async function generateTogether(prompt: string, seed: number): Promise<Buffer> {
  const res = await fetch('https://api.together.xyz/v1/images/generations', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${process.env.TOGETHER_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'black-forest-labs/FLUX.1-schnell',
      prompt,
      width: 512,
      height: 512,
      steps: 4,
      n: 1,
      seed,
      response_format: 'b64_json',
    }),
  });
  if (!res.ok) throw new Error(`together: HTTP ${res.status} ${await res.text()}`);
  const json = (await res.json()) as { data: { b64_json: string }[] };
  const b64 = json.data[0]?.b64_json;
  if (!b64) throw new Error('together: no b64_json in response');
  return Buffer.from(b64, 'base64');
}

async function generateReplicate(prompt: string, seed: number): Promise<Buffer> {
  // Low-credit accounts are throttled to 60 predictions/min (burst 5), so a
  // concurrency-4 pool trips 429s; honor retry_after with a capped retry
  // loop (429s are rejected before prediction creation — no charge).
  let res: Response;
  for (let attempt = 1; ; attempt++) {
    res = await fetch(
      'https://api.replicate.com/v1/models/black-forest-labs/flux-schnell/predictions',
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${process.env.REPLICATE_API_TOKEN}`,
          'Content-Type': 'application/json',
          Prefer: 'wait',
        },
        body: JSON.stringify({
          input: {
            prompt,
            seed,
            num_outputs: 1,
            aspect_ratio: '1:1',
            output_format: 'png',
            disable_safety_checker: false,
          },
        }),
      },
    );
    if (res.status !== 429 || attempt >= 8) break;
    const body = (await res.json()) as { retry_after?: number };
    await sleep(((body.retry_after ?? 6) + 1) * 1000);
  }
  if (!res.ok) throw new Error(`replicate: HTTP ${res.status} ${await res.text()}`);
  let prediction = (await res.json()) as {
    status: string;
    urls: { get: string };
    output: string | string[] | null;
  };

  // Prefer: wait usually resolves synchronously; poll if still processing
  // (1s intervals, capped at ~60s).
  const deadline = Date.now() + 60_000;
  while (
    (prediction.status === 'starting' || prediction.status === 'processing') &&
    Date.now() < deadline
  ) {
    await sleep(1000);
    const pollRes = await fetch(prediction.urls.get, {
      headers: { Authorization: `Bearer ${process.env.REPLICATE_API_TOKEN}` },
    });
    prediction = (await pollRes.json()) as typeof prediction;
  }
  if (prediction.status !== 'succeeded') {
    throw new Error(`replicate: prediction ended with status ${prediction.status}`);
  }

  const url = Array.isArray(prediction.output) ? prediction.output[0] : prediction.output;
  if (!url) throw new Error('replicate: no output URL in prediction');
  const imgRes = await fetch(url);
  if (!imgRes.ok) throw new Error(`replicate: HTTP ${imgRes.status} fetching output image`);
  return Buffer.from(await imgRes.arrayBuffer());
}

async function generate(prompt: string, seed: number): Promise<Buffer> {
  return PROVIDER === 'together' ? generateTogether(prompt, seed) : generateReplicate(prompt, seed);
}

/** Render a 16×16 mask upscaled to PREVIEW_PX² via an SVG of black cells on
 * white, through Resvg (mirrors render-scoring-pngs.ts's PNG rendering). */
function renderMaskPreview(front: boolean[][]): Buffer {
  const rects: string[] = [];
  for (let r = 0; r < SIZE; r++) {
    for (let c = 0; c < SIZE; c++) {
      if (front[r][c]) {
        rects.push(`<rect x="${c * CELL_PX}" y="${r * CELL_PX}" width="${CELL_PX}" height="${CELL_PX}"/>`);
      }
    }
  }
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="${PREVIEW_PX}" height="${PREVIEW_PX}">` +
    `<rect width="${PREVIEW_PX}" height="${PREVIEW_PX}" fill="white"/>` +
    `<g fill="black">${rects.join('')}</g></svg>`;
  return new Resvg(svg, { fitTo: { mode: 'width', value: PREVIEW_PX } }).render().asPng();
}

type ManifestEntry = {
  noun: string;
  seed: number;
  prompt: string;
  ok: boolean;
  thresholdUsed?: number;
  filledCells?: number;
  note?: string;
  error?: string;
};

async function main(): Promise<void> {
  const RUN_DIR = join(import.meta.dirname, '..', 'runs', OUT_RUN_ID);
  const RAW_DIR = join(RUN_DIR, 'raw');
  const MASKS_DIR = join(RUN_DIR, 'masks');
  const PREVIEWS_DIR = join(RUN_DIR, 'previews');
  for (const dir of [RUN_DIR, RAW_DIR, MASKS_DIR, PREVIEWS_DIR]) mkdirSync(dir, { recursive: true });

  console.log(`provider: ${PROVIDER}, ${candidates.length} images to generate`);

  const entries = await runPool(candidates, CONCURRENCY, async ({ noun, seed }) => {
    const stem = `${nounFileStem(noun)}-c${seed}`;
    const prompt = buildPrompt(NOUN_TABLE[noun]);
    const entry: ManifestEntry = { noun, seed, prompt, ok: false };
    try {
      const rawPath = join(RAW_DIR, `${stem}.png`);
      const reuse = SKIP_EXISTING && existsSync(rawPath);
      const png = reuse ? readFileSync(rawPath) : await generate(prompt, seed);
      if (reuse) entry.note = 'reused existing raw (skip-existing)';
      else writeFileSync(rawPath, png);

      const { pixels, width, height } = decodePng(png);
      const { front, thresholdUsed, filledCells, note } = pixelsToFrontMask(
        pixels,
        width,
        height,
        `${noun} c${seed}`,
        isInkDark,
      );

      const maskText = maskToRows(front).join('\n') + '\n';
      writeFileSync(join(MASKS_DIR, `${stem}.txt`), maskText);
      writeFileSync(join(PREVIEWS_DIR, `${stem}.png`), renderMaskPreview(front));

      entry.ok = true;
      entry.thresholdUsed = thresholdUsed;
      entry.filledCells = filledCells;
      if (note) entry.note = entry.note ? `${entry.note}; ${note}` : note;
      console.log(`${stem}: ok, ${filledCells} filled cells, threshold ${thresholdUsed}${entry.note ? ` (${entry.note})` : ''}`);
    } catch (err) {
      entry.error = err instanceof Error ? err.message : String(err);
      console.error(`${stem}: FAILED — ${entry.error}`);
    }
    return entry;
  });

  const okCount = entries.filter((e) => e.ok).length;
  const manifest = {
    id: OUT_RUN_ID,
    date: MANIFEST_DATE,
    provider: PROVIDER,
    model: 'black-forest-labs/FLUX.1-schnell',
    candidates: entries,
  };
  writeFileSync(join(RUN_DIR, 'gen.json'), JSON.stringify(manifest, null, 2) + '\n');

  console.log(`\ngenerated ${okCount}/${entries.length} images ok → ${RUN_DIR}`);
}

main();
