import fs from 'node:fs';
import path from 'node:path';
import Anthropic from '@anthropic-ai/sdk';
import { parseAsciiLayers } from './parseAsciiLayers.ts';
import { extractRevised } from './extractRevised.ts';
import { PROMPT_DRAFT } from './promptDraft.ts';
import { PROMPT_REVISE } from './promptRevise.ts';
import { analyze } from '../src/voxel/analyze.ts';
import { shiftToGround } from '../src/voxel/transform.ts';
import type { VoxelGrid } from '../src/voxel/types.ts';

const MODEL = 'claude-opus-4-7';
const MAX_RETRIES = 4;
const RETRY_BASE_MS = 1200;

function loadEnvLocal(): void {
  const file = path.resolve(process.cwd(), '.env.local');
  if (!fs.existsSync(file)) return;
  for (const raw of fs.readFileSync(file, 'utf-8').split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (key && !process.env[key]) {
      process.env[key] = value;
    }
  }
}

function slugify(term: string): string {
  return term
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

type AnyClient = InstanceType<typeof Anthropic>;
type CreateArgs = Parameters<AnyClient['messages']['create']>[0];
type CreateResult = Awaited<ReturnType<AnyClient['messages']['create']>>;

async function createWithRetry(client: AnyClient, args: CreateArgs): Promise<CreateResult> {
  let lastErr: unknown;
  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    try {
      return await client.messages.create(args);
    } catch (err) {
      lastErr = err;
      const status = (err as { status?: number }).status;
      const retryable = status === 429 || status === 500 || status === 502 || status === 503 || status === 529;
      if (!retryable || attempt === MAX_RETRIES - 1) throw err;
      const delay = RETRY_BASE_MS * Math.pow(2, attempt) + Math.random() * 400;
      console.log(`  retry ${attempt + 1}/${MAX_RETRIES - 1} after ${Math.round(delay)}ms (status ${status})`);
      await sleep(delay);
    }
  }
  throw lastErr;
}

function textOf(response: CreateResult): string {
  const block = response.content.find(b => b.type === 'text');
  if (!block || block.type !== 'text') {
    throw new Error(`No text block in response: ${JSON.stringify(response.content)}`);
  }
  return block.text;
}

function logUsage(label: string, response: CreateResult): void {
  const u = response.usage;
  if (!u) return;
  const r = (u as { cache_read_input_tokens?: number }).cache_read_input_tokens ?? 0;
  const w = (u as { cache_creation_input_tokens?: number }).cache_creation_input_tokens ?? 0;
  console.log(`  ${label} usage: in=${u.input_tokens} out=${u.output_tokens} cache_read=${r} cache_write=${w}`);
}

function metricsLine(grid: VoxelGrid): string {
  const conn = analyze(grid);
  const parts: string[] = [];
  parts.push(`${grid.voxels.length} voxels (target 25–60)`);
  parts.push(`${conn.components} connected component${conn.components === 1 ? '' : 's'} (target 1)`);
  parts.push(`${conn.touchesGround ? 'touches' : 'does NOT touch'} the ground (y=0)`);
  parts.push(`${conn.floatingCount} voxels lack direct support directly below (informational; cantilever is OK if connected)`);
  return parts.join('. ') + '.';
}

function gridToTs(term: string, draft: string, critique: string, revised: string, grid: VoxelGrid): string {
  const safe = (s: string) => s.replace(/\*\//g, '* /');
  const header = `// Generated by scripts/generate.ts (draft+revise) for prompt: ${JSON.stringify(term)}
// Draft, critique, and revised layers preserved at the bottom of this file.
import type { VoxelGrid } from '../types.ts';

export const term = ${JSON.stringify(term)};

const grid: VoxelGrid = {
  size: 8,
  voxels: [
`;
  const body = grid.voxels
    .map(v => `    { x: ${v.x}, y: ${v.y}, z: ${v.z}, color: '${v.color}' },`)
    .join('\n');
  const footer = `
  ],
};

export default grid;

/* draft (pass 1):
${safe(draft)}
*/

/* critique (pass 2):
${safe(critique)}
*/

/* revised (pass 2):
${safe(revised)}
*/
`;
  return header + body + footer;
}

async function generate(client: AnyClient, term: string): Promise<void> {
  console.log(`→ generating "${term}"…`);

  // Pass 1 — draft. Single-shot voxel layers, 3-example anchored.
  const passOne = await createWithRetry(client, {
    model: MODEL,
    max_tokens: 4096,
    system: [
      { type: 'text', text: PROMPT_DRAFT, cache_control: { type: 'ephemeral' } },
    ],
    messages: [{ role: 'user', content: term }],
  } as unknown as CreateArgs);
  const draftText = textOf(passOne);
  logUsage('draft', passOne);

  const draftGrid = shiftToGround(parseAsciiLayers(draftText));
  const draftConn = analyze(draftGrid);
  console.log(`  draft: ${draftGrid.voxels.length} voxels — components=${draftConn.components} touchesGround=${draftConn.touchesGround}`);

  // Pass 2 — critique + revise. Show Claude its draft + objective metrics,
  // ask for self-critique then revised layers.
  const revisePrompt = `Here is your first draft. Objective metrics: ${metricsLine(draftGrid)}\n\nNow critique your draft (does it read clearly as "${term}"? what's missing or wrong?), then output the revised 8 layers in the format described.`;

  const passTwo = await createWithRetry(client, {
    model: MODEL,
    max_tokens: 4096,
    system: [
      { type: 'text', text: PROMPT_REVISE, cache_control: { type: 'ephemeral' } },
    ],
    messages: [
      { role: 'user', content: term },
      { role: 'assistant', content: draftText },
      { role: 'user', content: revisePrompt },
    ],
  } as unknown as CreateArgs);
  const reviseText = textOf(passTwo);
  logUsage('revise', passTwo);

  const { critique, revised } = extractRevised(reviseText);
  const grid = shiftToGround(parseAsciiLayers(revised));
  const conn = analyze(grid);
  console.log(`  revised: ${grid.voxels.length} voxels — components=${conn.components} touchesGround=${conn.touchesGround}`);
  if (critique) {
    const oneLine = critique.replace(/\s+/g, ' ').slice(0, 200);
    console.log(`  critique: ${oneLine}${critique.length > 200 ? '…' : ''}`);
  }

  if (conn.components > 1 || !conn.touchesGround) {
    console.warn(`  ⚠ revised model is still invalid: components=${conn.components} touchesGround=${conn.touchesGround}`);
  }

  const slug = slugify(term);
  const outDir = path.resolve(process.cwd(), 'src/voxel/generated');
  fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, `${slug}.ts`);
  fs.writeFileSync(outFile, gridToTs(term, draftText, critique, revised, grid));
  console.log(`  wrote ${path.relative(process.cwd(), outFile)}`);
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    console.error('usage: npm run generate -- "<term>" ["<term2>" ...]');
    process.exit(1);
  }
  loadEnvLocal();
  if (!process.env.ANTHROPIC_API_KEY) {
    throw new Error('ANTHROPIC_API_KEY is not set. Add it to .env.local.');
  }
  const client = new Anthropic();
  for (const term of args) {
    try {
      await generate(client, term);
    } catch (err) {
      console.error(`✗ "${term}" failed:`, err instanceof Error ? err.message : err);
    }
  }
}

main();
