// CLI: term → Replicate text-to-3D → GLB mesh → voxelize → src/voxel/generated/<slug>.ts
//
//   npm run generate3d -- "mushroom" "lighthouse"
//   npm run generate3d -- --schema        # print the model's input schema
//
// Needs REPLICATE_API_TOKEN in .env.local. Override the model with
// BLAWX_3D_MODEL (owner/name). Raw meshes land in out/3d/ (gitignored).

import fs from 'node:fs';
import path from 'node:path';
import Anthropic from '@anthropic-ai/sdk';
import { parseGlb } from './glb.ts';
import { voxelizeTriangles } from './voxelizeMesh.ts';
import { colorize } from './colorize.ts';
import { analyze } from '../src/voxel/analyze.ts';
import type { VoxelGrid } from '../src/voxel/types.ts';

const MODEL = process.env.BLAWX_3D_MODEL ?? 'tencent/hunyuan-3d-3.1';
const API = 'https://api.replicate.com/v1';
const POLL_MS = 3000;
const TIMEOUT_MS = 10 * 60 * 1000;

type AnyClient = InstanceType<typeof Anthropic>;

function loadEnvLocal(): void {
  const file = path.resolve(process.cwd(), '.env.local');
  if (!fs.existsSync(file)) return;
  for (const raw of fs.readFileSync(file, 'utf-8').split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (key && !process.env[key]) {
      process.env[key] = value;
    }
  }
}

function slugify(term: string): string {
  return term
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function authHeaders(): Record<string, string> {
  return {
    Authorization: `Bearer ${process.env.REPLICATE_API_TOKEN}`,
    'Content-Type': 'application/json',
  };
}

async function getJson(url: string): Promise<unknown> {
  const res = await fetch(url, { headers: authHeaders() });
  if (!res.ok) throw new Error(`GET ${url} → ${res.status}: ${await res.text()}`);
  return res.json();
}

async function printSchema(): Promise<void> {
  const model = (await getJson(`${API}/models/${MODEL}`)) as {
    latest_version?: { openapi_schema?: { components?: { schemas?: Record<string, unknown> } } };
  };
  const schemas = model.latest_version?.openapi_schema?.components?.schemas ?? {};
  console.log(`# ${MODEL} input schema\n`);
  console.log(JSON.stringify(schemas['Input'] ?? schemas, null, 2));
}

type Prediction = {
  id: string;
  status: 'starting' | 'processing' | 'succeeded' | 'failed' | 'canceled';
  output?: unknown;
  error?: unknown;
  urls?: { get?: string };
};

async function createPrediction(term: string): Promise<Prediction> {
  const res = await fetch(`${API}/models/${MODEL}/predictions`, {
    method: 'POST',
    headers: { ...authHeaders(), Prefer: 'wait=60' },
    // face_count: schema minimum — we downsample to 8³, detail is wasted.
    body: JSON.stringify({ input: { prompt: term, face_count: 40000 } }),
  });
  if (!res.ok) {
    throw new Error(
      `create prediction failed (${res.status}): ${await res.text()}\n` +
        `If the input schema rejects "prompt", run: npm run generate3d -- --schema`,
    );
  }
  return (await res.json()) as Prediction;
}

async function waitForPrediction(p: Prediction): Promise<Prediction> {
  const started = Date.now();
  let current = p;
  while (current.status === 'starting' || current.status === 'processing') {
    if (Date.now() - started > TIMEOUT_MS) {
      throw new Error(`prediction ${current.id} timed out after ${TIMEOUT_MS / 1000}s`);
    }
    await sleep(POLL_MS);
    if (!current.urls?.get) throw new Error('prediction has no polling URL');
    current = (await getJson(current.urls.get)) as Prediction;
    console.log(`  status: ${current.status}`);
  }
  return current;
}

/** Find the mesh URL anywhere in the prediction output. Prefers .glb. */
function findMeshUrl(output: unknown): string | null {
  const urls: string[] = [];
  const walk = (value: unknown): void => {
    if (typeof value === 'string') {
      if (value.startsWith('http')) urls.push(value);
    } else if (Array.isArray(value)) {
      value.forEach(walk);
    } else if (value && typeof value === 'object') {
      Object.values(value).forEach(walk);
    }
  };
  walk(output);
  return urls.find(u => u.split('?')[0].endsWith('.glb')) ?? urls[0] ?? null;
}

function gridToTs(
  term: string,
  meshUrl: string,
  predictionId: string,
  grid: VoxelGrid,
  colorizeRaw: string | null,
): string {
  const header = `// Generated by scripts/generate3d.ts (${MODEL}) for prompt: ${JSON.stringify(term)}
// prediction: ${predictionId}
// mesh: ${meshUrl}
import type { VoxelGrid } from '../types.ts';

export const term = ${JSON.stringify(term)};

const grid: VoxelGrid = {
  size: 8,
  voxels: [
`;
  const body = grid.voxels
    .map(v => `    { x: ${v.x}, y: ${v.y}, z: ${v.z}, color: '${v.color}' },`)
    .join('\n');
  const safe = (s: string) => s.replace(/\*\//g, '* /');
  const footer = colorizeRaw
    ? `\n  ],\n};\n\nexport default grid;\n\n/* colorize (raw LLM response):\n${safe(colorizeRaw)}\n*/\n`
    : '\n  ],\n};\n\nexport default grid;\n';
  return header + body + footer;
}

async function generate(
  term: string,
  opts: { fromCache: boolean; anthropic: AnyClient | null },
): Promise<void> {
  const slug = slugify(term);
  const meshDir = path.resolve(process.cwd(), 'out/3d');
  fs.mkdirSync(meshDir, { recursive: true });
  const meshFile = path.join(meshDir, `${slug}.glb`);

  let meshBuffer: ArrayBuffer;
  let meshUrl = '';
  let predictionId = '';

  if (opts.fromCache && fs.existsSync(meshFile)) {
    console.log(`→ "${term}" using cached mesh ${path.relative(process.cwd(), meshFile)}`);
    meshBuffer = fs.readFileSync(meshFile).buffer.slice(0) as ArrayBuffer;
    meshUrl = `file://${meshFile}`;
    predictionId = 'cached';
  } else {
    if (opts.fromCache) {
      console.log(`→ "${term}": --from-cache requested but no GLB at ${path.relative(process.cwd(), meshFile)}; falling through to Replicate`);
    }
    console.log(`→ generating "${term}" via ${MODEL}…`);
    const created = await createPrediction(term);
    const done = await waitForPrediction(created);
    if (done.status !== 'succeeded') {
      throw new Error(`prediction ${done.id} ${done.status}: ${JSON.stringify(done.error)}`);
    }
    const url = findMeshUrl(done.output);
    if (!url) {
      throw new Error(`no mesh URL in output: ${JSON.stringify(done.output).slice(0, 500)}`);
    }
    console.log(`  mesh: ${url}`);
    const meshRes = await fetch(url);
    if (!meshRes.ok) throw new Error(`mesh download failed: ${meshRes.status}`);
    meshBuffer = await meshRes.arrayBuffer();
    fs.writeFileSync(meshFile, Buffer.from(meshBuffer));
    console.log(`  saved ${path.relative(process.cwd(), meshFile)} (${meshBuffer.byteLength} bytes)`);
    meshUrl = url;
    predictionId = done.id;
  }

  const triangles = parseGlb(meshBuffer);
  console.log(`  parsed ${triangles.length} triangles`);

  const { grid: whiteGrid, stats } = voxelizeTriangles(triangles);
  const conn = analyze(whiteGrid);
  console.log(
    `  voxelized: ${whiteGrid.voxels.length} voxels ` +
      `(surface=${stats.surfaceCells} interior=${stats.interiorFilled} dropped=${stats.droppedCells}) — ` +
      `components=${conn.components} touchesGround=${conn.touchesGround}`,
  );

  let grid = whiteGrid;
  let colorizeRaw: string | null = null;
  if (opts.anthropic) {
    const result = await colorize(opts.anthropic, term, whiteGrid);
    grid = result.grid;
    colorizeRaw = result.raw;
  } else {
    console.log('  colorize: skipped (no ANTHROPIC_API_KEY)');
  }

  const outDir = path.resolve(process.cwd(), 'src/voxel/generated');
  fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, `${slug}.ts`);
  fs.writeFileSync(outFile, gridToTs(term, meshUrl, predictionId, grid, colorizeRaw));
  console.log(`  wrote ${path.relative(process.cwd(), outFile)}`);
}

async function main(): Promise<void> {
  const rawArgs = process.argv.slice(2);
  loadEnvLocal();
  const fromCache = rawArgs.includes('--from-cache');
  const noColor = rawArgs.includes('--no-color');
  const terms = rawArgs.filter(a => !a.startsWith('--'));

  if (rawArgs.includes('--schema')) {
    if (!process.env.REPLICATE_API_TOKEN) {
      throw new Error('REPLICATE_API_TOKEN is not set. Add it to .env.local.');
    }
    await printSchema();
    return;
  }
  if (terms.length === 0) {
    console.error('usage: npm run generate3d -- [--from-cache] [--no-color] "<term>" ["<term2>" ...]');
    process.exit(1);
  }
  if (!fromCache && !process.env.REPLICATE_API_TOKEN) {
    throw new Error('REPLICATE_API_TOKEN is not set. Add it to .env.local (or pass --from-cache to use cached GLBs).');
  }

  let anthropic: AnyClient | null = null;
  if (!noColor) {
    if (!process.env.ANTHROPIC_API_KEY) {
      console.warn('⚠ ANTHROPIC_API_KEY is not set; colorize step will be skipped. Add it to .env.local or pass --no-color to silence this.');
    } else {
      anthropic = new Anthropic();
    }
  }

  for (const term of terms) {
    try {
      await generate(term, { fromCache, anthropic });
    } catch (err) {
      console.error(`✗ "${term}" failed:`, err instanceof Error ? err.message : err);
    }
  }
}

main();
