import fs from 'node:fs';
import path from 'node:path';
import Anthropic from '@anthropic-ai/sdk';
import { parseAsciiLayers } from './parseAsciiLayers.ts';
import { parseSilhouettes } from './parseSilhouettes.ts';
import { PASS1_PROMPT } from './promptPass1.ts';
import { PASS2_PROMPT } from './promptPass2.ts';
import { analyze } from '../src/voxel/analyze.ts';
import { shiftToGround } from '../src/voxel/transform.ts';
import type { VoxelGrid } from '../src/voxel/types.ts';

const MODEL = 'claude-opus-4-7';
const MAX_RETRIES = 4;
const RETRY_BASE_MS = 1200;
const MAX_FIX_ATTEMPTS = 2;

function loadEnvLocal(): void {
  const file = path.resolve(process.cwd(), '.env.local');
  if (!fs.existsSync(file)) return;
  for (const raw of fs.readFileSync(file, 'utf-8').split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (key && !process.env[key]) {
      process.env[key] = value;
    }
  }
}

function slugify(term: string): string {
  return term
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

type AnyClient = InstanceType<typeof Anthropic>;
type CreateArgs = Parameters<AnyClient['messages']['create']>[0];
type CreateResult = Awaited<ReturnType<AnyClient['messages']['create']>>;

async function createWithRetry(client: AnyClient, args: CreateArgs): Promise<CreateResult> {
  let lastErr: unknown;
  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    try {
      return await client.messages.create(args);
    } catch (err) {
      lastErr = err;
      const status = (err as { status?: number }).status;
      const retryable = status === 429 || status === 500 || status === 502 || status === 503 || status === 529;
      if (!retryable || attempt === MAX_RETRIES - 1) throw err;
      const delay = RETRY_BASE_MS * Math.pow(2, attempt) + Math.random() * 400;
      console.log(`  retry ${attempt + 1}/${MAX_RETRIES - 1} after ${Math.round(delay)}ms (status ${status})`);
      await sleep(delay);
    }
  }
  throw lastErr;
}

function textOf(response: CreateResult): string {
  const block = response.content.find(b => b.type === 'text');
  if (!block || block.type !== 'text') {
    throw new Error(`No text block in response: ${JSON.stringify(response.content)}`);
  }
  return block.text;
}

function logUsage(label: string, response: CreateResult): void {
  const u = response.usage;
  if (!u) return;
  const r = (u as { cache_read_input_tokens?: number }).cache_read_input_tokens ?? 0;
  const w = (u as { cache_creation_input_tokens?: number }).cache_creation_input_tokens ?? 0;
  console.log(`  ${label} usage: in=${u.input_tokens} out=${u.output_tokens} cache_read=${r} cache_write=${w}`);
}

function gridToTs(term: string, plan: string, layers: string, grid: VoxelGrid): string {
  const header = `// Generated by scripts/generate.ts (two-pass) for prompt: ${JSON.stringify(term)}
// Pass 1 (silhouettes) and pass 2 (layers) preserved at the bottom of this file.
import type { VoxelGrid } from '../types.ts';

export const term = ${JSON.stringify(term)};

const grid: VoxelGrid = {
  size: 8,
  voxels: [
`;
  const body = grid.voxels
    .map(v => `    { x: ${v.x}, y: ${v.y}, z: ${v.z}, color: '${v.color}' },`)
    .join('\n');
  const safePlan = plan.replace(/\*\//g, '* /');
  const safeLayers = layers.replace(/\*\//g, '* /');
  const footer = `
  ],
};

export default grid;

/* pass 1 — silhouettes:
${safePlan}
*/

/* pass 2 — voxel layers:
${safeLayers}
*/
`;
  return header + body + footer;
}

async function generate(client: AnyClient, term: string): Promise<void> {
  console.log(`→ generating "${term}"…`);

  // Same as pass 2: when adaptive thinking is enabled the model sometimes
  // spends the entire token budget thinking and never emits silhouettes.
  // Without thinking the model still "thinks through" by drawing the
  // silhouettes themselves — they ARE the plan.
  const passOne = await createWithRetry(client, {
    model: MODEL,
    max_tokens: 4096,
    system: [
      { type: 'text', text: PASS1_PROMPT, cache_control: { type: 'ephemeral' } },
    ],
    messages: [{ role: 'user', content: term }],
  } as unknown as CreateArgs);
  const planText = textOf(passOne);
  logUsage('pass1', passOne);

  const silhouettes = parseSilhouettes(planText);
  const occupied = (g: typeof silhouettes.front) => g.flat().filter(c => c !== null).length;
  console.log(`  silhouette cells: front=${occupied(silhouettes.front)} side=${occupied(silhouettes.side)} top=${occupied(silhouettes.top)}`);

  // Pass 2 is mechanical realization, not design. Even low-effort adaptive
  // thinking sometimes consumed the entire token budget and returned only
  // thinking blocks (no text). Omit thinking entirely.
  const passTwoMessages: Array<{ role: 'user' | 'assistant'; content: string }> = [
    { role: 'user', content: term },
    { role: 'assistant', content: planText },
    { role: 'user', content: 'Now produce the 8 voxel layers consistent with those silhouettes.' },
  ];

  let layersText = '';
  let grid: VoxelGrid = { size: 8, voxels: [] };
  let attempts = 0;
  while (attempts <= MAX_FIX_ATTEMPTS) {
    const passTwo = await createWithRetry(client, {
      model: MODEL,
      max_tokens: 4096,
      system: [
        { type: 'text', text: PASS2_PROMPT, cache_control: { type: 'ephemeral' } },
      ],
      messages: passTwoMessages,
    } as unknown as CreateArgs);
    layersText = textOf(passTwo);
    logUsage(`pass2${attempts > 0 ? `-fix${attempts}` : ''}`, passTwo);

    grid = shiftToGround(parseAsciiLayers(layersText));
    const conn = analyze(grid);
    console.log(`  ${grid.voxels.length} voxels — components=${conn.components} touchesGround=${conn.touchesGround}`);

    const broken = grid.voxels.length === 0 || conn.components > 1 || !conn.touchesGround;
    if (!broken || attempts === MAX_FIX_ATTEMPTS) break;

    // Build a corrective follow-up. Same conversation; model sees its own
    // broken output and the specific problem.
    const issues: string[] = [];
    if (grid.voxels.length === 0) issues.push('the output was empty — re-emit the 8 layers');
    if (conn.components > 1) issues.push(`there are ${conn.components} disconnected parts — every voxel must be face-adjacent to at least one other in the same piece`);
    if (!conn.touchesGround) issues.push('no voxel sits on the ground (y=0) — at least one voxel must have y=0');
    const correction = `The model you produced is invalid: ${issues.join('; ')}. Re-emit the 8 voxel layers, fixed. Same silhouettes; same colors; just a SINGLE connected piece touching the ground. Output only the 8 layers.`;
    passTwoMessages.push({ role: 'assistant', content: layersText });
    passTwoMessages.push({ role: 'user', content: correction });
    attempts++;
  }

  const finalConn = analyze(grid);
  if (finalConn.components > 1 || !finalConn.touchesGround) {
    console.warn(`⚠ still broken after ${attempts} fix attempt(s): components=${finalConn.components} touchesGround=${finalConn.touchesGround}`);
  }

  const slug = slugify(term);
  const outDir = path.resolve(process.cwd(), 'src/voxel/generated');
  fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, `${slug}.ts`);
  fs.writeFileSync(outFile, gridToTs(term, planText, layersText, grid));
  console.log(`  wrote ${path.relative(process.cwd(), outFile)}`);
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    console.error('usage: npm run generate -- "<term>" ["<term2>" ...]');
    process.exit(1);
  }
  loadEnvLocal();
  if (!process.env.ANTHROPIC_API_KEY) {
    throw new Error('ANTHROPIC_API_KEY is not set. Add it to .env.local.');
  }
  const client = new Anthropic();
  for (const term of args) {
    try {
      await generate(client, term);
    } catch (err) {
      console.error(`✗ "${term}" failed:`, err instanceof Error ? err.message : err);
    }
  }
}

main();
