import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseSilhouettes, viewToAscii } from './parseSilhouettes.ts';

const DUCK_PASS1 = `front:
........
........
...YY...
...YKR..
...YYY..
.YYYYY..
.YYYYYY.
..YYYY..

side:
........
........
...YY...
...RR...
...YY...
...YY...
...YY...
...YY...

top:
........
........
........
.YYYYRY.
.YYYYRY.
........
........
........`;

test('parses all three duck views', () => {
  const s = parseSilhouettes(DUCK_PASS1);
  // y=4 row in front view should be ...YBR..
  // front[3] is y=4 from the top (rows: y=7,6,5,4,3,2,1,0)
  const y4Row = s.front[3];
  assert.equal(y4Row[3], 'yellow');
  assert.equal(y4Row[4], 'black');
  assert.equal(y4Row[5], 'red');
  // top view, z=3 has beak red at x=5
  const z3 = s.top[3];
  assert.equal(z3[5], 'red');
});

test('roundtrips through viewToAscii', () => {
  const s = parseSilhouettes(DUCK_PASS1);
  const front = viewToAscii(s.front);
  assert.ok(front.includes('...YKR..'));
  const side = viewToAscii(s.side);
  assert.ok(side.includes('...RR...'));
  const top = viewToAscii(s.top);
  assert.ok(top.includes('.YYYYRY.'));
});

test('missing view returns empty grid', () => {
  const text = `front:
YYYYYYYY
........
........
........
........
........
........
........`;
  const s = parseSilhouettes(text);
  assert.equal(s.front[0][0], 'yellow');
  assert.equal(s.side[0][0], null);
  assert.equal(s.top[0][0], null);
});

test('accepts lowercase headers and palette letters', () => {
  const text = `FRONT:
yyyyyyyy
........
........
........
........
........
........
........

SIDE:
rrrrrrrr
........
........
........
........
........
........
........

TOP:
bbbbbbbb
........
........
........
........
........
........
........`;
  const s = parseSilhouettes(text);
  assert.equal(s.front[0][0], 'yellow');
  assert.equal(s.side[0][0], 'red');
  assert.equal(s.top[0][0], 'blue');
});

test('strips markdown fences', () => {
  const text = '```\nfront:\n' + 'YYYYYYYY\n'.repeat(8) +
    '\nside:\n' + '........\n'.repeat(8) +
    '\ntop:\n' + '........\n'.repeat(8) +
    '```';
  const s = parseSilhouettes(text);
  assert.equal(s.front[0][0], 'yellow');
  assert.equal(s.front[7][7], 'yellow');
});

test('rows past 8 are ignored', () => {
  const text = `front:
YYYYYYYY
RRRRRRRR
........
........
........
........
........
........
BBBBBBBB
BBBBBBBB

side:
........
........
........
........
........
........
........
........

top:
........
........
........
........
........
........
........
........`;
  const s = parseSilhouettes(text);
  // Only first 8 rows kept
  assert.equal(s.front[0][0], 'yellow');
  assert.equal(s.front[1][0], 'red');
  assert.equal(s.front[7][0], null);
});

test('tolerates space-separated cells', () => {
  const text = `front:
. . . Y Y . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .

side:
........
........
........
........
........
........
........
........

top:
........
........
........
........
........
........
........
........`;
  const s = parseSilhouettes(text);
  assert.equal(s.front[0][3], 'yellow');
  assert.equal(s.front[0][4], 'yellow');
  assert.equal(s.front[0][0], null);
});

test('short rows pad with empty', () => {
  const text = `front:
YYY
........
........
........
........
........
........
........

side:
........
........
........
........
........
........
........
........

top:
........
........
........
........
........
........
........
........`;
  const s = parseSilhouettes(text);
  assert.equal(s.front[0][0], 'yellow');
  assert.equal(s.front[0][2], 'yellow');
  assert.equal(s.front[0][3], null);
});
