export const PASS2_PROMPT = `You already designed the object as three orthographic silhouettes (front, side, top). Now realize it as 8 voxel layers.

THE GRID (same as before)
- 8×8×8 voxels. Integer coordinates 0..7.
- Y is up. X is left-to-right. Z is back-to-front (Z=7 closest to camera).
- Palette letters: Y yellow, R red, B blue, G green, W white, K black, L lightGray, . empty.

OUTPUT FORMAT
Exactly 8 layers, bottom (y=0) to top (y=7). Each layer is 8 rows of 8 single-character cells. Row index = z (z=0 at the top of the grid, z=7 at the bottom). Column index = x (x=0 left, x=7 right). No spaces. No prose. No markdown fences. No commentary.

CONSISTENCY WITH THE SILHOUETTES
The voxels you place must reproduce the silhouettes:
- For each (x, y), the voxel with maximum Z at that column must match the cell at (x, y) in the front view.
- For each (z, y), the voxel with maximum X at that row must match the cell at (z, y) in the side view.
- For each (x, z), the voxel with maximum Y at that footprint must match the cell at (x, z) in the top view.
- Empty cells in a view mean no voxel along that ray.

HARD RULES
1. Single connected piece. Every voxel face-adjacent to at least one other. Some voxel at y=0.
2. Don't pad voxels into empty space the silhouettes don't claim.
3. Internal (hidden) voxels can be any color from your model's palette, but prefer continuity with the visible faces.
4. If the three silhouettes don't fully constrain an interior voxel, pick the most sensible color — usually the surrounding body color.

WORKED EXAMPLE
Given these duck silhouettes:

front:
........
........
...YY...
...YKR..
...YYY..
.YYYYY..
.YYYYYY.
..YYYY..

side:
........
........
...YY...
...RR...
...YY...
...YY...
...YY...
...YY...

top:
........
........
........
.YYYYRY.
.YYYYRY.
........
........
........

Realize as:

y=0
........
........
........
..YYYY..
..YYYY..
........
........
........

y=1
........
........
........
.YYYYYY.
.YYYYYY.
........
........
........

y=2
........
........
........
.YYYYY..
.YYYYY..
........
........
........

y=3
........
........
........
...YYY..
...YYY..
........
........
........

y=4
........
........
........
...YYR..
...YKR..
........
........
........

y=5
........
........
........
...YY...
...YY...
........
........
........

y=6
........
........
........
........
........
........
........
........

y=7
........
........
........
........
........
........
........
........

Now produce the 8 layers for the current model. Output only the layers, nothing else.`;
